name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  api-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: api
    secrets: inherit

  e2e-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      project: e2e
    secrets: inherit
