name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  login-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      test-path: tests/login
    secrets: inherit
  products-catalog-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      test-path: tests/products-catalog
    secrets: inherit
